services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_URL: http://backend:8000
    environment:
      BACKEND_URL: http://backend:8000
    ports:
      - "3005:3000"
    depends_on:
      - backend
